## Nations Configuration

## EXAMPLE
#  nationexample: [YAML keys are always lowercase. Name entries are in double-quotes, while other fields are not.]
#    display: [Display settings for the nation.]
#      name: "Nation Example" [Formatted nation name // No color codes in this field.]
#      color: &f [Color code here. Standard color codes only.]
#      item: white_banner [Namespaced item name here. Can be default Minecraft items as well as scripted Denizen Items (dItems).]
#    status: [Status settings for the nation.]
#      joinable: true [Is the nation joinable? "true" OR "false".]
#      event: false [Is the nation part of the story/an event? "true" OR "false".]

# NATIONS
nations:
  #Nation 1
  nation1:
    display:
      name: "Nation 1"
      color: &c
      item: red_banner
    status:
      joinable: true
      event: false